// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUQk-BcppFuOjAvpTbvVsG6uOl3UgCs5Q',
    appId: '1:1001735501918:web:c40b66b2d3646518161ccf',
    messagingSenderId: '1001735501918',
    projectId: 'coffeeapp-85e45',
    authDomain: 'coffeeapp-85e45.firebaseapp.com',
    storageBucket: 'coffeeapp-85e45.firebasestorage.app',
    measurementId: 'G-HC8G7SCXKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq-dv9IlazEj1V0pQw-TyRriWGh2MvxJg',
    appId: '1:1001735501918:android:d580f9ab0bb5ceb0161ccf',
    messagingSenderId: '1001735501918',
    projectId: 'coffeeapp-85e45',
    storageBucket: 'coffeeapp-85e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDISpOuZaik9HaFM41L7K8JElvQhyGAzR0',
    appId: '1:1001735501918:ios:fa29efdbaa58d758161ccf',
    messagingSenderId: '1001735501918',
    projectId: 'coffeeapp-85e45',
    storageBucket: 'coffeeapp-85e45.firebasestorage.app',
    iosBundleId: 'com.example.enjaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDISpOuZaik9HaFM41L7K8JElvQhyGAzR0',
    appId: '1:1001735501918:ios:fa29efdbaa58d758161ccf',
    messagingSenderId: '1001735501918',
    projectId: 'coffeeapp-85e45',
    storageBucket: 'coffeeapp-85e45.firebasestorage.app',
    iosBundleId: 'com.example.enjaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUQk-BcppFuOjAvpTbvVsG6uOl3UgCs5Q',
    appId: '1:1001735501918:web:1d7ba3f4ac39d0f8161ccf',
    messagingSenderId: '1001735501918',
    projectId: 'coffeeapp-85e45',
    authDomain: 'coffeeapp-85e45.firebaseapp.com',
    storageBucket: 'coffeeapp-85e45.firebasestorage.app',
    measurementId: 'G-105JZK49GD',
  );
}
